// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8rfDt9Vq7_dnLWskkpJV6TqujGxIuH94',
    appId: '1:553124643634:web:c53238b4a27c6a127c0d2b',
    messagingSenderId: '553124643634',
    projectId: 'syncmesh-audio',
    authDomain: 'syncmesh-audio.firebaseapp.com',
    storageBucket: 'syncmesh-audio.firebasestorage.app',
    measurementId: 'G-MH4ENSS64C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZVaISGdYAITzD2LPiRSnFP1wG89708H8',
    appId: '1:553124643634:android:0c7ff23657db82a57c0d2b',
    messagingSenderId: '553124643634',
    projectId: 'syncmesh-audio',
    storageBucket: 'syncmesh-audio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFDx35luQZt3kJC6L0O6EXh_NAmfwhKGw',
    appId: '1:553124643634:ios:2d2aec944025ba947c0d2b',
    messagingSenderId: '553124643634',
    projectId: 'syncmesh-audio',
    storageBucket: 'syncmesh-audio.firebasestorage.app',
    iosBundleId: 'io.syncmesh.audio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFDx35luQZt3kJC6L0O6EXh_NAmfwhKGw',
    appId: '1:553124643634:ios:2d2aec944025ba947c0d2b',
    messagingSenderId: '553124643634',
    projectId: 'syncmesh-audio',
    storageBucket: 'syncmesh-audio.firebasestorage.app',
    iosBundleId: 'io.syncmesh.audio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8rfDt9Vq7_dnLWskkpJV6TqujGxIuH94',
    appId: '1:553124643634:web:59f27fa8af867c777c0d2b',
    messagingSenderId: '553124643634',
    projectId: 'syncmesh-audio',
    authDomain: 'syncmesh-audio.firebaseapp.com',
    storageBucket: 'syncmesh-audio.firebasestorage.app',
    measurementId: 'G-PP60PW1DZ3',
  );
}
